version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: getthreaded-app-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/getthreaded
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app:cached
      - nextjs_cache:/app/.next
      - node_modules_cache:/app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - getthreaded-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:7.0-jammy
    container_name: getthreaded-mongodb-dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=getthreaded
    volumes:
      - mongodb-data-dev:/data/db
      - mongodb-config-dev:/data/configdb
    networks:
      - getthreaded-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  getthreaded-network:
    driver: bridge

volumes:
  mongodb-data-dev:
    driver: local
  mongodb-config-dev:
    driver: local
  nextjs_cache:
    driver: local
  node_modules_cache:
    driver: local