version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: getthreaded:latest
    container_name: getthreaded-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/getthreaded
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
    networks:
      - getthreaded-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {if (r.statusCode !== 200) process.exit(1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:7.0-jammy
    container_name: getthreaded-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=getthreaded
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      - getthreaded-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  getthreaded-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
  mongodb-config:
    driver: local